// ==========================================
// Blockspace Forum — Site Configuration
// ==========================================
// AUTO-GENERATED by build.py from content/*.md
// To update links, edit this file directly.
// To update posts, edit content/*.md and re-run build.py.

const SITE_CONFIG = {
  name: "Blockspace Forum",
  tagline: "Forum built to improve the Ethereum transaction journey.",
  description: "Education, research, and open source tooling for the infrastructure that moves Ethereum's transactions. This forum ships.",

  banner: {
    active: true,
    text: "New: Cannes 2026 Workshop Recap",
    link: "learn/events/cannes-2026.html",
  },

  links: {
    twitter: "https://x.com/blockspaceforum",
    github: "https://github.com/blockspace-forum",
    youtube: "https://www.youtube.com/@BlockspaceForum",
    ethresearch: "",
    website: "",
    discord: "",
    telegram: "",
  },

  research: [
    {
      title: "An Observation on Ethereum's Blockspace Market",
      authors: "Kubi M., Alex T., Kevin L., Justin D.",
      date: "Dec 2025",
      summary: "Structural analysis of PBS economics, robustness, performance, and services.",
      url: "https://ethresear.ch/t/an-observation-on-ethereum-s-blockspace-market/23669",
      featured: true,
    },
    {
      title: "Block Constraints Sharing: Multi-Relay Inclusion Lists & Beyond",
      authors: "Blockspace Forum",
      date: "2025",
      summary: "Inter-relay constraint coordination for inclusion list enforcement. Foreshadows relay consensus mechanisms for sub-slot auctions.",
      url: "https://ethresear.ch/t/block-constraints-sharing-multi-relay-inclusion-lists-beyond/22752",
      featured: true
    },
    {
      title: "Block Merging: Boosting Value & Censorship Resistance",
      authors: "Michael, Kubi",
      date: "Jun 2025",
      summary: "Merging top-of-block segments from multiple relays into a single, more valuable, censorship-resistant block.",
      url: "https://ethresear.ch/t/relay-block-merging-boosting-value-censorship-resistance/22592",
      featured: true,
    },
    {
      title: "Relay Inclusion Lists",
      authors: "Michael, Kubi",
      date: "Apr 2025",
      summary: "A mechanism for relays to enforce transaction inclusion, improving censorship resistance without protocol changes.",
      url: "https://ethresear.ch/t/relay-inclusion-lists/22218",
      featured: true
    },
  ],

  tooling: {
    operate: [
      { name: "Commit-Boost", description: "Validator sidecar for PBS, preconfirmations, and commitments.", url: "https://github.com/commit-boost/commit-boost-client" },
      { name: "Helix", description: "Open source relay implementation.", url: "https://github.com/gattaca-com/helix" },
      { name: "rbuilder", description: "Open source block builder.", url: "https://github.com/flashbots/rbuilder" },
    ],
    observe: [
      { name: "txdelay.xyz", description: "Transaction delay visualization", url: "https://txdelay.xyz/" },
      { name: "bids.pics", description: "Relay and builder market share", url: "https://bids.pics/" },
      { name: "Rated Explorer", description: "Validator monitoring", url: "https://explorer.rated.network/" },
      { name: "relayscan.io", description: "Relay monitoring and statistics", url: "https://www.relayscan.io/" },
      { name: "commit-boost.org", description: "Commit-Boost validator sidecar dashboard", url: "https://www.commit-boost.org/" },
    ],
  },

  contribute: [
    { name: "commit-boost-client", lang: "Rust", description: "Validator sidecar for PBS, preconfirmations, and commitments.", url: "https://github.com/commit-boost/commit-boost-client" },
    { name: "helix", lang: "Rust", description: "Open source relay implementation.", url: "https://github.com/gattaca-com/helix" },
    { name: "rbuilder", lang: "Rust", description: "Open source block builder.", url: "https://github.com/flashbots/rbuilder" },
  ],

  events: [
    {
      title: "Blockspace Forum Cannes 2026",
      location: "Cannes, France",
      year: "2026",
      description: "The second Blockspace Forum gathering. Workshops, research presentations, and working sessions on the future of Ethereum's blockspace market.",
      video: "https://www.youtube.com/embed/ixJDu_h4unQ",
      status: "Workshop Summary",
      link: "learn/events/cannes-2026.html",
      videos: [
        {
          title: "Kick-Off — Kubi Mensah (Gattaca)",
          summary: "Forum framing: Ethereum's core product is blockspace. The mission is conversations to specs to MVPs to production code.",
          video: "https://www.youtube.com/embed/W279wYFI0EI",
        },
        {
          title: "I can see all your transactions: Privacy and what institutions need — Mo (EF)",
          summary: "The EF's 50-person privacy lab and new institutional team. Private reads, writes, and proving. 15.8 billion in tokenized assets on L1.",
          video: "https://www.youtube.com/embed/AnfW2Rk97FE",
        },
        {
          title: "The proof is in the building — Sean (Sigma Prime)",
          summary: "Generating validity proofs in under 10 seconds. How the ePBS slot structure creates a natural proving window. Parallel proving and L2 horizontal scaling.",
          video: "https://www.youtube.com/embed/Lw_z2bjD_cM",
        },
        {
          title: "ePBS Fireside Chat — Terence (Prysm) & Alex (ultra sound)",
          summary: "Devnet 0 complete, Devnet 1 started. PTC deadline debate. Does ePBS kill relays? Testing is the bottleneck. Q2/Q3 estimate for mainnet.",
          video: "https://www.youtube.com/embed/B-rk9FISVEE",
        },
        {
          title: "Gwei GPT: Ethereum transaction rails in an AI world — Alex Stokes (EF)",
          summary: "How AI reshapes every layer: intent explosion, wallet disappearance, solver markets, builder vertical integration, and the security arms race.",
          video: "https://www.youtube.com/embed/kWUwyg0J-Dc",
        },
        {
          title: "Post-Quantum & ETH Vision — Fede (Lambda Class) & Justin Drake (EF)",
          summary: "Neutral atoms: 6K qubits today, 26K theoretically. Post-quantum heartbeat design. ETH as the internet of value. Shielded L1 transfers.",
          video: "https://www.youtube.com/embed/UMKEV_g15OY",
        },
        {
          title: "Inside the pipeline: Data driven truths of Ethereum's supply chain — Lorenzo (Gattaca) & Christian (ultra sound)",
          summary: "50ms CEX-DEX replacement latency. 7M bundles per hour at peak. 90% of blocks via relays. Timing games quantified. MEV concentrating in top 1% of blocks.",
          video: "https://www.youtube.com/embed/di5a6BF2bII",
        },
        {
          title: "Builder Services & Exclusive Flow — Panel",
          summary: "Builders compete on trust, execution guarantees, privacy, and latency. The exclusive order flow flywheel. Platform business model thinking.",
          video: "https://www.youtube.com/embed/-dJhPc4aKbc",
        },
        {
          title: "Issuance and why the transaction pipeline should care — Jerome (Ethereum France)",
          summary: "The diamond rule: max 0.5% issuance. 33.3M ETH staked and trending to 40%. Security problems, LST substitution risk, and the snowball effect.",
          video: "https://www.youtube.com/embed/E8f8DHzpDnQ",
        },
        {
          title: "Institutional Investment — Zach (Grayscale) & Nixo (EF)",
          summary: "ETH as commodity investing. Trust over speed and scale. Stablecoins plus tokenization equals Ethereum. The macro backdrop and dollar skepticism.",
          video: "https://www.youtube.com/embed/ehYESl6Pdd4",
        },
      ],
    },
    {
      title: "Blockspace Forum @ Devconnect BA",
      location: "Buenos Aires, Argentina",
      year: "2025",
      description: "The inaugural event. Comparing notes on what's working, what's brittle, and what's being left on the table in Ethereum's blockspace pipeline.",
      header_description: "Blockspace Forum's first event in Buenos Aires, 2025.",
      status: "Workshop Summary",
      link: "https://ethresear.ch/t/an-observation-on-ethereum-s-blockspace-market/23669",
    },
  ],

  posts: [
    {
      slug: "what-if",
      title: "What If?",
      subtitle: "Introducing the Blockspace Forum",
      date: "2026-02-11",
      source: "https://x.com/blockspaceforum/status/2021591198062756119",
    },
    {
      slug: "the-other-gwei",
      title: "The Other Gwei",
      subtitle: "A journey down the transaction rails of Ethereum",
      date: "2026-02-17",
      source: "https://x.com/blockspaceforum/status/2023761721622765728",
    },
    {
      slug: "keep-validators-decentralized",
      title: "Keep Ethereum's Validator Set Decentralized",
      subtitle: "How PBS preserved validator decentralization",
      date: "2026-02-19",
      source: "https://x.com/blockspaceforum/status/2024509838445990029",
    },
    {
      slug: "structural-gaps",
      title: "Three Years of PBS",
      subtitle: "A survey of the structural gaps",
      date: "2026-02-25",
      source: "https://x.com/blockspaceforum/status/2026671024348054009",
    },
    {
      slug: "economics",
      title: "Align the Incentives",
      subtitle: "Economics: Align the incentives to align the outcome",
      date: "2026-02-26",
      source: "https://x.com/blockspaceforum/status/2027037604332384379",
    },
    {
      slug: "robustness",
      title: "A Counterparty Without Counterparty Risk",
      subtitle: "Ethereum's robustness and where the rails fall short",
      date: "2026-03-09",
      source: "https://x.com/blockspaceforum/status/2031019543020163080",
    },
    {
      slug: "performance",
      title: "Wait",
      subtitle: "Performance bottlenecks in the block construction pipeline",
      date: "2026-03-20",
      source: "https://x.com/blockspaceforum/status/2034999394555003080",
    }
  ],
};
